language: ruby
rvm: 2.5
dist: trusty
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- 'wget -O ./_data/news.csv $(bundle exec yaml get news-feed -F=_config.yml) || :'
- 'wget -O ./_data/events.csv $(bundle exec yaml get events-feed -F=_config.yml) || :'
- 'wget -O ./_data/profiles.csv $(bundle exec yaml get faculty-feed -F=_config.yml) || :'
- 'wget -O ./_data/media-mentions.csv $(bundle exec yaml get media-mentions-feed -F=_config.yml) || :'
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href --external_only
  --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      secure: qgR33NlpMqXKfI8XYVEJUM6+OWwUBrvMK5Qo1PRsUp0AlQnmsY/Hasa2QkZ08viyePr0tlez6GjoxT0qNKKKTUpw7wW+yQVmEM4J3ZaRQYemTbxDtBAktrNwJCKzUzA8u41KV+l2vmHZXr4fklHT1+0kDsbP9PB3sEgLLgQmCdLY/uZIoSegls6xQKJg/863t0ocuQpmvbey6Raakg06iZWHnTiUahDbs0vXvQZClVO7dmmryZ6Y8TsV1GK5x3ySAUbTSn61SKXrD3SqfX1pYeZbCMaPd9d+hd3NRoPmXx/uS4rxF/OzeX8hbOW5lEFLS23+trT95cKgHKPnLZu+sk/3/4K9r5cYwPi20JmAvEQ3Vk2IH1UA4sg+QyrtH2CYcClcR689LpGK9Pj2I74938sM47021jla1ttiiyOPWz3P19FviqxfQeSxKMDH+JPCNgtkfB7M+gzEuih/Z2DIdAM2ZbZv5xuPcfzpopR2fd2ZMwwMYx9zzqvf//iCw0I9dz5MKqy8q0a/IflTZCr4QynolGRi/ixbCIEjHOSzSBcsrewhcRnx4Flac3Mct3XCAI64d3LhmOfp1FoM/jgV5lmJvHI/N5b3f7sob6hlJxjCbdK3TEJI722IgldggU89OTkxG9WFuVNMMBl6arMO3zQzdZhBeptjj5swff1IkL0=
    on_success: always
